import type { GraphProjectionSchema } from "../lib/api/generated";

export const networkFixture: GraphProjectionSchema = {
  clusters: [
    { id: "organization:alpha", label: "Alpha", memberCount: 3 },
    { id: "organization:beta", label: "Beta", memberCount: 2 },
  ],
  edges: [
    {
      currentActivation: 0.9,
      edgeType: "DIRECT",
      opacity: "HIGH",
      relationshipState: "CLOSE",
      relationshipStrength: 0.82,
      sourcePersonId: "person-001",
      style: "SOLID",
      targetPersonId: "person-002",
      width: "THICK",
    },
    {
      currentActivation: 0.2,
      edgeType: "DIRECT",
      opacity: "LOW",
      relationshipState: "DORMANT",
      relationshipStrength: 0.4,
      sourcePersonId: "person-001",
      style: "DASHED",
      targetPersonId: "person-003",
      width: "THIN",
    },
    {
      edgeType: "POTENTIAL_PATH",
      opacity: "MUTED",
      sourcePersonId: "person-002",
      style: "DOTTED",
      targetPersonId: "person-004",
      width: "MUTED",
    },
    {
      edgeType: "POTENTIAL_PATH",
      opacity: "MUTED",
      sourcePersonId: "person-003",
      style: "DOTTED",
      targetPersonId: "person-005",
      width: "MUTED",
    },
  ],
  focalPersonId: "person-001",
  meta: {
    generatedAt: "2026-08-09T00:00:00Z",
    hops: 2,
    lens: "DEFAULT",
    oneHopCount: 2,
    projectionVersion: "graph-projection-v0.1.0",
    totalNetworkSize: 42,
    twoHopCount: 2,
    visibleNodeCount: 5,
  },
  nodes: [
    {
      avatarUrl: null,
      clusterId: "organization:alpha",
      displayName: "Mina Nakamura",
      hop: 0,
      isPotential: false,
      personId: "person-001",
      relevance: 1,
      relationshipState: null,
      shortRole: "Product Lead",
    },
    {
      avatarUrl: null,
      clusterId: "organization:alpha",
      displayName: "Aoi Sato",
      hop: 1,
      isPotential: false,
      personId: "person-002",
      relevance: 0.88,
      relationshipState: "CLOSE",
      shortRole: "Designer",
    },
    {
      avatarUrl: null,
      clusterId: "organization:beta",
      displayName: "Ren Ito",
      hop: 1,
      isPotential: false,
      personId: "person-003",
      relevance: 0.48,
      relationshipState: "DORMANT",
      shortRole: "Engineer",
    },
    {
      avatarUrl: null,
      clusterId: "organization:alpha",
      displayName: "Yui Mori",
      hop: 2,
      isPotential: true,
      personId: "person-004",
      relevance: 0.3,
      relationshipState: null,
      shortRole: "Researcher",
    },
    {
      avatarUrl: null,
      clusterId: "organization:beta",
      displayName: "Kai Abe",
      hop: 2,
      isPotential: true,
      personId: "person-005",
      relevance: 0.25,
      relationshipState: null,
      shortRole: null,
    },
  ],
};
