"""Add NC-005 canonical fact and relationship-profile persistence.

Revision ID: 20260809_0002
Revises: 20260808_0001
Create Date: 2026-08-09 17:23:17
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "20260809_0002"
down_revision: str | Sequence[str] | None = "20260808_0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "activities",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_activities")),
    )
    op.create_table(
        "communities",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_communities")),
    )
    op.create_table(
        "organization_units",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organization_units")),
    )
    op.create_table(
        "project_contexts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "ended_at IS NULL OR ended_at >= started_at",
            name=op.f("ck_project_contexts_project_interval"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_project_contexts")),
    )
    op.create_table(
        "skills",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_skills")),
    )
    op.create_table(
        "people",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("joined_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "hire_type",
            sa.Enum(
                "GRADUATE",
                "EXPERIENCED",
                "OTHER",
                name="hire_type",
                native_enum=False,
                create_constraint=True,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("primary_organization_unit_id", sa.Uuid(), nullable=True),
        sa.Column("role", sa.String(length=255), nullable=True),
        sa.Column("career_level", sa.String(length=255), nullable=True),
        sa.Column("location", sa.String(length=255), nullable=True),
        sa.Column("avatar_url", sa.String(length=2048), nullable=True),
        sa.ForeignKeyConstraint(
            ["primary_organization_unit_id"],
            ["organization_units.id"],
            name=op.f("fk_people_primary_organization_unit_id_organization_units"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_people")),
    )
    op.create_index(
        "ix_people_primary_organization", "people", ["primary_organization_unit_id"], unique=False
    )
    op.create_table(
        "community_memberships",
        sa.Column("person_id", sa.Uuid(), nullable=False),
        sa.Column("community_id", sa.Uuid(), nullable=False),
        sa.Column("joined_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("left_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "left_at IS NULL OR left_at >= joined_at",
            name=op.f("ck_community_memberships_membership_interval"),
        ),
        sa.ForeignKeyConstraint(
            ["community_id"],
            ["communities.id"],
            name=op.f("fk_community_memberships_community_id_communities"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["person_id"],
            ["people.id"],
            name=op.f("fk_community_memberships_person_id_people"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("person_id", "community_id", name=op.f("pk_community_memberships")),
    )
    op.create_table(
        "interaction_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "channel",
            sa.Enum(
                "DIGITAL",
                "ANALOG",
                name="interaction_channel",
                native_enum=False,
                create_constraint=True,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column(
            "type",
            sa.Enum(
                "TEAMS_CHAT",
                "EMAIL",
                "ONLINE_1ON1",
                "GROUP_MEETING",
                "OFFICE_CHAT",
                "COFFEE",
                "LUNCH",
                "DINNER",
                "COMMUNITY",
                "ACTIVITY",
                "OTHER",
                name="interaction_type",
                native_enum=False,
                create_constraint=True,
                length=24,
            ),
            nullable=False,
        ),
        sa.Column(
            "source",
            sa.Enum(
                "SYSTEM",
                "SELF_REPORTED",
                "MUTUAL_CONFIRMED",
                "INFERRED",
                name="interaction_source",
                native_enum=False,
                create_constraint=True,
                length=24,
            ),
            nullable=False,
        ),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("conversation_participant_count", sa.Integer(), nullable=True),
        sa.Column(
            "duration_bucket",
            sa.Enum(
                "SHORT",
                "MEDIUM",
                "LONG",
                name="duration_bucket",
                native_enum=False,
                create_constraint=True,
                length=16,
            ),
            nullable=True,
        ),
        sa.Column("activity_id", sa.Uuid(), nullable=True),
        sa.Column("community_id", sa.Uuid(), nullable=True),
        sa.Column("project_id", sa.Uuid(), nullable=True),
        sa.Column("initiator_person_id", sa.Uuid(), nullable=True),
        sa.Column("created_by_person_id", sa.Uuid(), nullable=True),
        sa.Column("source_system", sa.String(length=100), nullable=True),
        sa.Column("external_event_id", sa.String(length=255), nullable=True),
        sa.CheckConstraint(
            "(source_system IS NULL AND external_event_id IS NULL) OR "
            "(source_system IS NOT NULL AND external_event_id IS NOT NULL)",
            name=op.f("ck_interaction_events_source_identifier_complete"),
        ),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1",
            name=op.f("ck_interaction_events_confidence_unit"),
        ),
        sa.CheckConstraint(
            "conversation_participant_count IS NULL OR conversation_participant_count >= 2",
            name=op.f("ck_interaction_events_conversation_participants_minimum"),
        ),
        sa.CheckConstraint(
            "created_at >= occurred_at", name=op.f("ck_interaction_events_created_after_occurrence")
        ),
        sa.ForeignKeyConstraint(
            ["activity_id"],
            ["activities.id"],
            name=op.f("fk_interaction_events_activity_id_activities"),
        ),
        sa.ForeignKeyConstraint(
            ["community_id"],
            ["communities.id"],
            name=op.f("fk_interaction_events_community_id_communities"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by_person_id"],
            ["people.id"],
            name=op.f("fk_interaction_events_created_by_person_id_people"),
        ),
        sa.ForeignKeyConstraint(
            ["initiator_person_id"],
            ["people.id"],
            name=op.f("fk_interaction_events_initiator_person_id_people"),
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project_contexts.id"],
            name=op.f("fk_interaction_events_project_id_project_contexts"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_interaction_events")),
        sa.UniqueConstraint(
            "source_system", "external_event_id", name="uq_interaction_events_source_external"
        ),
    )
    op.create_index(
        "ix_interaction_events_occurred_at", "interaction_events", ["occurred_at"], unique=False
    )
    op.create_table(
        "person_activities",
        sa.Column("person_id", sa.Uuid(), nullable=False),
        sa.Column("activity_id", sa.Uuid(), nullable=False),
        sa.Column("declared_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "visibility",
            sa.Enum(
                "PRIVATE",
                "NETWORK",
                "ORGANIZATION",
                name="visibility",
                native_enum=False,
                create_constraint=True,
                length=16,
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["activity_id"],
            ["activities.id"],
            name=op.f("fk_person_activities_activity_id_activities"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["person_id"],
            ["people.id"],
            name=op.f("fk_person_activities_person_id_people"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("person_id", "activity_id", name=op.f("pk_person_activities")),
    )
    op.create_table(
        "person_external_identifiers",
        sa.Column("person_id", sa.Uuid(), nullable=False),
        sa.Column("source_system", sa.String(length=100), nullable=False),
        sa.Column("external_id", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(
            ["person_id"],
            ["people.id"],
            name=op.f("fk_person_external_identifiers_person_id_people"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "person_id", "source_system", "external_id", name=op.f("pk_person_external_identifiers")
        ),
        sa.UniqueConstraint(
            "source_system", "external_id", name="uq_person_external_identifiers_source_external"
        ),
    )
    op.create_table(
        "person_skills",
        sa.Column("person_id", sa.Uuid(), nullable=False),
        sa.Column("skill_id", sa.Uuid(), nullable=False),
        sa.Column("declared_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["person_id"],
            ["people.id"],
            name=op.f("fk_person_skills_person_id_people"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["skill_id"],
            ["skills.id"],
            name=op.f("fk_person_skills_skill_id_skills"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("person_id", "skill_id", name=op.f("pk_person_skills")),
    )
    op.create_table(
        "project_participations",
        sa.Column("person_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "ended_at IS NULL OR ended_at >= started_at",
            name=op.f("ck_project_participations_participation_interval"),
        ),
        sa.ForeignKeyConstraint(
            ["person_id"],
            ["people.id"],
            name=op.f("fk_project_participations_person_id_people"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project_contexts.id"],
            name=op.f("fk_project_participations_project_id_project_contexts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("person_id", "project_id", name=op.f("pk_project_participations")),
    )
    op.create_table(
        "relationship_profiles",
        sa.Column("person_a_id", sa.Uuid(), nullable=False),
        sa.Column("person_b_id", sa.Uuid(), nullable=False),
        sa.Column("current_activation", sa.Float(), nullable=False),
        sa.Column("historical_depth", sa.Float(), nullable=False),
        sa.Column("digital_evidence", sa.Float(), nullable=False),
        sa.Column("analog_evidence", sa.Float(), nullable=False),
        sa.Column("social_context", sa.Float(), nullable=False),
        sa.Column("reciprocity", sa.Float(), nullable=False),
        sa.Column("channel_diversity", sa.Float(), nullable=False),
        sa.Column("relationship_strength", sa.Float(), nullable=False),
        sa.Column(
            "state",
            sa.Enum(
                "NEW",
                "CLOSE",
                "ACTIVE",
                "WEAK",
                "DORMANT",
                "RECONNECTED",
                name="relationship_state",
                native_enum=False,
                create_constraint=True,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("first_meaningful_interaction_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_meaningful_interaction_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expected_cadence_days", sa.Float(), nullable=False),
        sa.Column("dormancy_ratio", sa.Float(), nullable=False),
        sa.Column("data_confidence", sa.Float(), nullable=False),
        sa.Column("model_version", sa.String(length=100), nullable=False),
        sa.Column("calculated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "analog_evidence >= 0 AND analog_evidence <= 1",
            name=op.f("ck_relationship_profiles_analog_evidence_unit"),
        ),
        sa.CheckConstraint(
            "channel_diversity >= 0 AND channel_diversity <= 1",
            name=op.f("ck_relationship_profiles_channel_diversity_unit"),
        ),
        sa.CheckConstraint(
            "current_activation >= 0 AND current_activation <= 1",
            name=op.f("ck_relationship_profiles_current_activation_unit"),
        ),
        sa.CheckConstraint(
            "data_confidence >= 0 AND data_confidence <= 1",
            name=op.f("ck_relationship_profiles_data_confidence_unit"),
        ),
        sa.CheckConstraint(
            "digital_evidence >= 0 AND digital_evidence <= 1",
            name=op.f("ck_relationship_profiles_digital_evidence_unit"),
        ),
        sa.CheckConstraint(
            "dormancy_ratio >= 0", name=op.f("ck_relationship_profiles_nonnegative_dormancy")
        ),
        sa.CheckConstraint(
            "expected_cadence_days > 0", name=op.f("ck_relationship_profiles_positive_cadence")
        ),
        sa.CheckConstraint(
            "first_meaningful_interaction_at <= last_meaningful_interaction_at",
            name=op.f("ck_relationship_profiles_meaningful_interval"),
        ),
        sa.CheckConstraint(
            "historical_depth >= 0 AND historical_depth <= 1",
            name=op.f("ck_relationship_profiles_historical_depth_unit"),
        ),
        sa.CheckConstraint(
            "last_meaningful_interaction_at <= calculated_at",
            name=op.f("ck_relationship_profiles_calculated_after_interaction"),
        ),
        sa.CheckConstraint(
            "person_a_id < person_b_id", name=op.f("ck_relationship_profiles_canonical_pair")
        ),
        sa.CheckConstraint(
            "reciprocity >= 0 AND reciprocity <= 1",
            name=op.f("ck_relationship_profiles_reciprocity_unit"),
        ),
        sa.CheckConstraint(
            "relationship_strength >= 0 AND relationship_strength <= 1",
            name=op.f("ck_relationship_profiles_relationship_strength_unit"),
        ),
        sa.CheckConstraint(
            "social_context >= 0 AND social_context <= 1",
            name=op.f("ck_relationship_profiles_social_context_unit"),
        ),
        sa.ForeignKeyConstraint(
            ["person_a_id"],
            ["people.id"],
            name=op.f("fk_relationship_profiles_person_a_id_people"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["person_b_id"],
            ["people.id"],
            name=op.f("fk_relationship_profiles_person_b_id_people"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "person_a_id", "person_b_id", name=op.f("pk_relationship_profiles")
        ),
    )
    op.create_index(
        "ix_relationship_profiles_model_version",
        "relationship_profiles",
        ["model_version"],
        unique=False,
    )
    op.create_index(
        "ix_relationship_profiles_state", "relationship_profiles", ["state"], unique=False
    )
    op.create_table(
        "user_relationship_feedback",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("person_a_id", sa.Uuid(), nullable=False),
        sa.Column("person_b_id", sa.Uuid(), nullable=False),
        sa.Column("created_by_person_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "created_by_person_id = person_a_id OR created_by_person_id = person_b_id",
            name=op.f("ck_user_relationship_feedback_creator_in_pair"),
        ),
        sa.CheckConstraint(
            "person_a_id < person_b_id", name=op.f("ck_user_relationship_feedback_canonical_pair")
        ),
        sa.ForeignKeyConstraint(
            ["created_by_person_id"],
            ["people.id"],
            name=op.f("fk_user_relationship_feedback_created_by_person_id_people"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["person_a_id"],
            ["people.id"],
            name=op.f("fk_user_relationship_feedback_person_a_id_people"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["person_b_id"],
            ["people.id"],
            name=op.f("fk_user_relationship_feedback_person_b_id_people"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_relationship_feedback")),
    )
    op.create_index(
        "ix_user_relationship_feedback_pair",
        "user_relationship_feedback",
        ["person_a_id", "person_b_id"],
        unique=False,
    )
    op.create_table(
        "interaction_participants",
        sa.Column("interaction_event_id", sa.Uuid(), nullable=False),
        sa.Column("person_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["interaction_event_id"],
            ["interaction_events.id"],
            name=op.f("fk_interaction_participants_interaction_event_id_interaction_events"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["person_id"],
            ["people.id"],
            name=op.f("fk_interaction_participants_person_id_people"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "interaction_event_id", "person_id", name=op.f("pk_interaction_participants")
        ),
    )
    op.create_index(
        "ix_interaction_participants_person",
        "interaction_participants",
        ["person_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_interaction_participants_person", table_name="interaction_participants")
    op.drop_table("interaction_participants")
    op.drop_index("ix_user_relationship_feedback_pair", table_name="user_relationship_feedback")
    op.drop_table("user_relationship_feedback")
    op.drop_index("ix_relationship_profiles_state", table_name="relationship_profiles")
    op.drop_index("ix_relationship_profiles_model_version", table_name="relationship_profiles")
    op.drop_table("relationship_profiles")
    op.drop_table("project_participations")
    op.drop_table("person_skills")
    op.drop_table("person_external_identifiers")
    op.drop_table("person_activities")
    op.drop_index("ix_interaction_events_occurred_at", table_name="interaction_events")
    op.drop_table("interaction_events")
    op.drop_table("community_memberships")
    op.drop_index("ix_people_primary_organization", table_name="people")
    op.drop_table("people")
    op.drop_table("skills")
    op.drop_table("project_contexts")
    op.drop_table("organization_units")
    op.drop_table("communities")
    op.drop_table("activities")
    # ### end Alembic commands ###
